name: Pipeline Completo CI/CD

on:
  push:
    branches: [ "main" ] # Se activa al hacer push a main

jobs:
  # TRABAJO 1: Integración Continua (Testear)
  ci-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: pytest test.py

  # TRABAJO 2: Entrega Continua (Desplegar)
  cd-deploying:
    needs: ci-testing # Espera a que pasen los tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Paso A: Crear la imagen y subirla al registro
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/calculadora-devops:latest

      # Paso B: Entrar al servidor y actualizar
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Detener contenedor viejo (si existe)
            docker stop calculadora-web || true
            docker rm calculadora-web || true
            # 2. Descargar la nueva versión
            docker pull ${{ secrets.DOCKER_USERNAME }}/calculadora-devops:latest
            # 3. Arrancar la nueva versión
            docker run -d -p 5000:5000 --name calculadora-web ${{ secrets.DOCKER_USERNAME }}/calculadora-devops:latest
